'use strict'

export const START_SHAKE_ANIMATION_FOR_TREE = 'START_SHAKE_ANIMATION_FOR_TREE'
export const STOP_SHAKE_ANIMATION_FOR_TREE = 'STOP_SHAKE_ANIMATION_FOR_TREE'

export const CREATE_APPLES_FOR_TREE = 'CREATE_APPLES_FOR_TREE'
export const MOVE_APPLE_TREE_TO_BASKET = 'MOVE_APPLE_TREE_TO_BASKET'
